
// let age = 19;

// if (age >= 18) {
    //     console.log("You are an adult.");
    // }
    
        // let isStudent = true;
// if (isStudent) {
//     console.log("You are a student.");
// } else {
    //     console.log("You are not a student.");
    // }

let prices = 2200;
if(prices>=500){
    console.log("20% Discount")
}else if(prices>=200){
console.log("10%discount")
}else{
    console.log("Denied")
};
        // let marks = 75;
        // if (marks >= 80) {
    //     console.log("Grade: A");
    // } else if (marks >= 60) {
        //     console.log("Grade: B");
        // } else {
            //     console.log("Grade: C");
            // }

            // let age = 19;
                    // let isStudent = true;
// if (age >= 18) {
//     if (isStudent) {
//         console.log("You are an adult student.");
//     } else {
    //         console.log("You are an adult but not a student.");
    //     }
    // }
    
    // let weather = "rainy";
// switch (weather) {
    //     case "sunny":
    //         console.log("Wear sunglasses.");
//         break;
//     case "rainy":
//         console.log("Take an umbrella.");
//         break;
//     case "cold":
//         console.log("Wear a jacket.");
//         break;
//     default:
//         console.log("Enjoy your day!");
// }
//Q1
// let age = 17;
// if(age >=18){
//     console.log("you can vote") 
// }else{
//     console.log("YOU CANT VOTE ")
// }
//Q2
// let num =prompt("Enter the to find odd or even")
// if(num %=2){
// console.log("Odd")
// }else{
//     console.log("Even")
// }
//Q3
// let num =prompt("Enter number");
// if(num>0){
//     console.log("Positive");
// }else if(num<0){
//     console.log("Negative");
// }else 
// {
//     console.log("Zero");

// }
//Q4
// let num1 =2;
// let num2= 3;
// if(num1>num2){
//     console.log("NUM1 is bigger than num2")
// }else{
//     console.log("num2 is bigger")
// }
//Q5
// let mark = 60;
// switch (mark) {
//     case 90:
//         console.log("A+");
//         break;
//     case 80:
//         console.log("A");
//         break;
//     case 70:
//         console.log("B")
//         break;
//     case 60:
//         console.log("C")
//         break;
//     default:
//         console.log("FAIL")
//         break;
// }
//Q8
// let password = prompt("Enter the password")
// if(password==="Hamza2005"){
//     console.log("Correct")
// }else{
//     console.log("Incorrect")
// }
//Q9
let price = 200;
if(price>=500){
    console.log("20% Discount")
}else if(price>=200){
console.log("10%discount")
}else{
    console.log("Denied")
};
//Q10
    // let weather = "rainy";
// switch (weather) {
    //     case "sunny":
    //         console.log("Wear sunglasses.");
//         break;
//     case "rainy":
//         console.log("Take an umbrella.");
//         break;
//     case "cold":
//         console.log("Wear a jacket.");
//         break;
//     default:
//         console.log("Enjoy your day!");
// }


